### ISSUE TITLE
Accept full claim date/time

### ISSUE THREAD

**Issue by saphena** [ibauk/ebcfetch#4]
The existing parsing logic assumes manually entered four digit claimtime. Want to cater for optional full ISO8601 datetime/zone specification which would be supplied by some automated process.

**Comment by ibauk** [comment]
New Subject: RE == (\w+)\s+(\w+)\s+(\w+)\s+([[\d\:\.\-\+TZ]+)\s*(.*)

Full rally/local timezone support accepts RFC3339 date/time
